# Generated by Django 4.0.5 on 2022-06-27 14:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='카테고리명')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='상품 제목')),
                ('thumbnail', models.ImageField(upload_to='product/thumbnail/', verbose_name='썸네일')),
                ('description', models.TextField(verbose_name='상품 설명')),
                ('view_count', models.BigIntegerField(default=0, verbose_name='상품 조회수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 상태')),
                ('is_delete', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('category', models.ManyToManyField(to='product.category', verbose_name='카테고리')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='가격')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량')),
                ('is_discount', models.BooleanField(default=False, verbose_name='할인 여부')),
                ('discount_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='할인 가격')),
                ('discount_start_date', models.DateTimeField(blank=True, null=True, verbose_name='할인 시작일')),
                ('discount_end_date', models.DateTimeField(blank=True, null=True, verbose_name='할인 종료일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/image/', verbose_name='이미지')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품')),
            ],
        ),
    ]
