# Generated by Django 4.0.5 on 2022-06-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_is_seller_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_secession',
        ),
        migrations.AddField(
            model_name='user',
            name='is_approve',
            field=models.BooleanField(default=True, verbose_name='관리자 승인'),
        ),
    ]
